create table TICKETS(
TICKETID BIGINT NOT NULL AUTO_INCREMENT,
FLIGHTNUMBER VARCHAR(40) NOT NULL,
PASSENGERNAME VARCHAR(40) NOT NULL,
TIME DATE NOT NULL,
PRIMARY KEY (TICKETID)
);

select * from tickets